### ISSUE TITLE
GraphQL endpoint always returning `errors: []`

### ISSUE THREAD

**Issue by jycouet** [supabase-community/supabase-graphql-example#17]
Graphql endpoint always returning `errors: []`
Even when `data` is filled with valid content besides.

I wonder if it's the expected behavior?

**Comment by olirice** [comment]
that behavior is from the underlying postgres extension `pg_graphql` that provides the GraphQL API. It is expected to be resolved in a later release of that project since the default is technically overfetching

**Comment by olirice** [comment]
https://github.com/supabase/pg_graphql/pull/142
