### ISSUE TITLE
Is there any documentation about how did pg-trigger set?

### ISSUE THREAD

**Issue by igmyung** [supabase-community/supabase-graphql-example#34]
Is there any documentation about how did pg-trigger set?

**Comment by thorwebdev** [comment]
Are you referring to the triggers for the voting? They can be found in the schema: https://github.com/supabase-community/supabase-graphql-example/blob/main/data/db/schema.sql#L2115-L2126

**Comment by igmyung** [comment]
Yes. This was want i wanted. Thanks!
